### ISSUE TITLE
Compatibility issue with RandoPlus

### ISSUE THREAD

**Issue by The-furf-of-July** [Korzer420/LoreRandomizer#4]
The Shrine of Believers quest to kill all ghosts becomes impossible to complete if Ghost Essences are randomised via RandoPlus.
This is especially an issue in the case of ItemSync, where one player killing a ghost removes it from the other players' game. Currently it appears that one player must kill all ghosts in order for the objective to count as completed.

The main way I see to fix it is checking if that mod is in use.
From there, you can check the locations to make sure all ghost kill item checks are obtained/reachable.

**Comment by Korzer420** [comment]
Sorry for the late response. I don't really see the issue (without itemsync/scatternest at least) with the RandoPlus Ghosts. But I haven't looked deep into that interaction. But I'll remove the goal from the shrine if these ghost essences are randomized, just to be sure. Will be implemented in the next update

**Comment by Korzer420** [comment]
Fixed in LoreRando 0.3 (+ LoreCore 0.6)
